# Generated by Django 3.1.6 on 2021-03-10 19:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('melons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_id',
            field=models.UUIDField(default=uuid.UUID('b8997f08-de61-460b-be0a-f8fc7302d197'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comt_id',
            field=models.UUIDField(default=uuid.UUID('02ae03a0-06fd-4767-9024-46211f4ffdce'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comt_like',
            field=models.IntegerField(default=0),
        ),
    ]
