# Generated by Django 3.1.6 on 2021-03-10 19:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('melons', '0003_auto_20210310_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_id',
            field=models.UUIDField(default=uuid.UUID('4675b49d-a81e-43c6-a382-1909db13a17a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comt_id',
            field=models.UUIDField(default=uuid.UUID('2cf45689-e12c-400b-bd88-ce81b814fa6a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
