# Generated by Django 3.1.6 on 2021-03-10 20:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('melons', '0004_auto_20210310_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_id',
            field=models.UUIDField(default=uuid.UUID('c742f4ff-dc73-4556-ba51-85b230c1051e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comt_id',
            field=models.UUIDField(default=uuid.UUID('126094d6-c944-4506-99f1-d4255e276b30'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gold',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, default='Anonymous User', max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
