# Generated by Django 3.1.6 on 2021-03-10 20:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('melons', '0005_auto_20210310_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comt_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_id',
            field=models.UUIDField(default=uuid.UUID('b298651d-963d-4aff-b4b4-ca88824dc2a9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
