# Generated by Django 3.1.6 on 2021-02-09 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('graphic', models.ImageField(upload_to='')),
                ('has_mods', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('is_welfare', models.BooleanField()),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=320)),
                ('nickname', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
                ('resource', models.IntegerField()),
                ('avatar', models.ImageField(upload_to='')),
                ('user_tier', models.CharField(choices=[('STU', 'Student'), ('STF', 'Staff'), ('ADM', 'Admin'), ('WEL', 'Welfare')], default='STU', max_length=3)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='study_platform.course')),
            ],
        ),
        migrations.CreateModel(
            name='WelfareResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('percentage', models.IntegerField()),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='study_platform.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_platform.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_platform.user')),
            ],
        ),
        migrations.CreateModel(
            name='TeamBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(to='study_platform.User')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='study_platform.team')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='study_platform.user'),
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('is_tool', models.BooleanField()),
                ('description', models.TextField()),
                ('effect', models.CharField(choices=[('EMP', 'Empty'), ('POL', 'Police'), ('THF', 'Thief'), ('SHD', 'Shield'), ('BLN', 'Blind'), ('BST', 'Boost')], default='EMP', max_length=3)),
                ('graphic', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_platform.user')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='study_platform.user'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MUL', 'Multiple Choice'), ('FIB', 'Fill Blank')], max_length=3)),
                ('content', models.TextField()),
                ('answer', models.TextField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='study_platform.course')),
            ],
        ),
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('effect', models.CharField(max_length=20)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_platform.accessory')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='study_platform.user')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('STN', 'Study Note')], default='STN', max_length=3)),
                ('content', models.TextField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('upvotes', models.IntegerField()),
                ('participants', models.ManyToManyField(to='study_platform.User')),
                ('post_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_platform.college')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_platform.user')),
            ],
        ),
        migrations.AddField(
            model_name='accessory',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_platform.reward'),
        ),
    ]
