# Generated by Django 3.1.6 on 2021-03-09 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('resource', models.IntegerField(default=0)),
                ('avatar', models.ImageField(default='static/images/bex3.jpg', upload_to='')),
                ('date_of_birth', models.DateField(null=True)),
                ('user_tier', models.CharField(choices=[('STU', 'Student'), ('STF', 'Staff'), ('ADM', 'Admin'), ('WEL', 'Welfare')], default='STU', max_length=3)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='study_platform.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
