# Generated by Django 3.1.6 on 2021-03-09 14:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('study_platform', '0002_auto_20210309_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_id',
            field=models.UUIDField(default=uuid.UUID('14780cba-a753-4681-ab2f-e0ce831a9e96'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comt_id',
            field=models.UUIDField(default=uuid.UUID('0b9ebe5b-0bf2-4879-8863-4d033a7f9e78'), editable=False, primary_key=True, serialize=False),
        ),
    ]
