# Generated by Django 3.1.6 on 2021-03-05 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study_platform', '0004_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_type', models.IntegerField()),
                ('card_content', models.TextField()),
                ('card_creat_date', models.DateTimeField(auto_now_add=True)),
                ('card_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('post_id', models.UUIDField(default=uuid.UUID('b834dfaf-66ad-4d15-b193-6216b36502b6'), editable=False, primary_key=True, serialize=False)),
                ('post_tag', models.CharField(max_length=64)),
                ('post_pin', models.BooleanField(default=False)),
                ('post_title', models.CharField(max_length=64)),
                ('post_content', models.TextField()),
                ('post_time', models.DateTimeField(auto_now=True)),
                ('post_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('opt_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opt_type', models.CharField(default='TXT', max_length=3)),
                ('opt_content', models.CharField(max_length=512)),
                ('opt_isCorrect', models.BooleanField(default=False)),
                ('opt_cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_platform.card')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comt_id', models.UUIDField(default=uuid.UUID('1a102a3a-090f-4aa9-8ddb-183e7e628325'), editable=False, primary_key=True, serialize=False)),
                ('comt_type', models.CharField(max_length=1)),
                ('comt_pid', models.CharField(max_length=64)),
                ('comt_content', models.TextField()),
                ('comt_time', models.DateTimeField(auto_now=True)),
                ('comt_like', models.IntegerField()),
                ('comt_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('coll_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coll_title', models.CharField(max_length=64)),
                ('coll_description', models.CharField(max_length=512)),
                ('coll_creat_date', models.DateTimeField(auto_now_add=True)),
                ('coll_cards', models.ManyToManyField(to='study_platform.Card')),
                ('coll_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='study_platform.userprofile')),
            ],
        ),
    ]
