# Generated by Django 3.1.6 on 2021-03-05 17:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('study_platform', '0005_auto_20210305_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comt_id',
            field=models.UUIDField(default=uuid.UUID('fec9341e-d2ba-4911-aee3-7742ccd79c92'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='poster',
            name='post_id',
            field=models.UUIDField(default=uuid.UUID('7712494b-0f78-42ce-9697-bd1615ceaea9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='CardComment',
        ),
    ]
